# Site
name: 'Authing 官方博客'
description: 'Authing 为个人和企业提供安全的云端身份认证服务，是行业领先的身份认证云。'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/blog'
disqus: 'Authing 博客'
email: 'services@authing.cn'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    ivy:
      name:           谢扬
      site:           http://ivydom.com
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Sal, the author of Mundana, the theme you're currently previewing. I hope you like it!"
      email:          xieyang@authing.cn
      twitter:        http://ivydom.com

    cj:
      name:           廖长江
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    zuwei:
      name:           叶祖伟
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet   
      
    duxinshuai:
      name:           杜新帅
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet  
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]